# ----
# Site

title: Cook's Pot
url: "https://theclue.github.io"
baseurl: "/cookspot.it"
gtm_key: GTM-MHH5J4J
newsletter_action:
disqus_shortname:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Pentole sull'orlo di una crisi di nervi
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name: Cook's Pot
  links:
    - https://cookspot.it

# collections
collections:
  category:
    output: true

# -----
# Build

paginate: 10
paginate_path: "/:num/"
permalink: /:title

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      push_sidebar_down: true
      print_stylesheet: true
      comments: false
      show_related: true
      _options:
        content:
          width: 1560
          height: 2000
        featured_image:
          width: 1560
          height: 2000
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"
      push_sidebar_down: true
  -
    scope:
      path: ""
      type: "category"
    values:
      layout: "category"
      push_sidebar_down: true
      image_view: true

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS

_options:
  author_image:
    width: 400
    height: 400
